# Nome da aplicação
name: GitHub Pages
on:
    push:
        branches:
          - main
          
    pull_request:
        branches:
          - main

jobs:
    deploy:
        name: Deploy da Aplicação
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              sparse-checkout: .
          - name: Criar ambiente do node
            uses: actions/setup-node@v3
            with:
              node-version: 18
              cache: 'npm'
              cache-dependency-path: subdir/package-lock.json
          - name: Instalar dependências e executar o script de build
            run: |
              npm install i
              npm run build
          - name: Push git subdirectory as branch
            uses: s0/git-publish-subdir-action@v2.6.0
            
            env:
              REPO: self
              BRANCH: main
              FOLDER: dist
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
